### ISSUE TITLE
Not working on the windows version of metasploit

### ISSUE THREAD

**Issue by mattewfarel** [ElevenPaths/Eternalblue-Doublepulsar-Metasploit#43]
the script is written only for the linux version of metasploit , using wine for lunching the binaries , how about exploiting a windows machine from another windows machine ? did anyone try porting the script to the windows version of metasploit ?

**Comment by UrielRicardo** [comment]
@mattewfarel use this
https://github.com/misterch0c/shadowbroker 
example: https://www.youtube.com/watch?v=ZgvkNjNt4BM

**Comment by UrielRicardo** [comment]
@mattewfarel Please close issue.

**Comment by BlackCatNeo** [comment]
> @mattewfarel commented 24 days ago • edited
the script is written only for the linux version of metasploit , using wine for lunching the binaries , how about exploiting a windows machine from another windows machine ? did anyone try porting the script to the windows version of metasploit ?

You can remove all instances of the call to `wine` and changed the  ";" batch command character to "&" so that it works for Windows. But at the end of it, it still hits an issue of the target architecture is wrong even though I did set it to the correct target architecture.
